### ISSUE TITLE
Error in if (!(request_info$format == "")) { : argument is of length zero

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#13]
experiments = c("GC_T14_10.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "C003N351.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "C005VG51.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "S002R551.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "NBC_NC11_41.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "bmPCs-V156.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "S00BS451.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "S00D1DA1.CPG_methylation_calls.bs_call.GRCh38.20150707.wig", "S00D39A1.CPG_methylation_calls.bs_call.GRCh38.20150707.wig")

experiments_columns = list()
for (experiment_name in experiments) {
    experiments_columns[[experiment_name]] = "VALUE"
}

cpgs = deepblue.select_annotations(annotation_name="Cpg Islands", chromosome="chr22", start=0, end=18000000, genome="hg19")

request_id = deepblue.score_matrix(experiments_columns=experiments_columns, aggregation_function="mean", aggregation_regions_id=cpgs)

score_matrix = deepblue.download_request_data(request_id)

**Comment by mlist** [comment]
I'm not sure this commit really solves the problem. I changed this recently because sometimes format is just an empty string, e.g. in the example where we query for all genes with a wild card regular expression.

**Comment by felipealbrecht** [comment]
The genes will be selected in the 'select_genes' command.
The request format is specified in the 'get_regions' command. Every get_regions command must contain the format with columns.

Others options, like score_matrix, get_experiments_by_query, and count_regions, does not contain the format in the request information.

Please, create a issue in the DeepBlue server if format in the reques is empty.

**Comment by mlist** [comment]
Reopened the corresponding issue in DeepBlue

**Comment by felipealbrecht** [comment]
Okay, please, include an use case where I can execute.

**Comment by mlist** [comment]
The use case was already included

**Comment by felipealbrecht** [comment]
Which one? Sorry, I dont know what are you talking about.

On May 10 2016, at 11:20 pm, Markus List &lt;notifications@github.com&gt;
wrote:  

> The use case was already included

>

> —  
You are receiving this because you modified the open/close state.  
Reply to this email directly or [view it on GitHub](https://github.com/MPIICom
putationalEpigenetics/DeepBlueR/issues/13#issuecomment-218295217)![](https://g
ithub.com/notifications/beacon/AA9mawOPbUGKA8qNMV64opZ2ojGeAaeqks5qAPaegaJpZM4
IbbIf.gif)

**Comment by mlist** [comment]
https://github.com/MPIIComputationalEpigenetics/DeepBlue/issues/115
