### ISSUE TITLE
Organize the code for Bioconductor submission

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#14]
Before any commit, lets execute:
 R CMD check .
and
 R CMD BiocCheck .

and print here the results.

**Comment by felipealbrecht** [comment]
Commit a4321c8102068e89ed7584aa484b229b4336225b

⇒  R CMD check .
* using log directory ‘/home/albrecht/DeepBlue/DeepBlueR/..Rcheck’
* using R version 3.2.2 (2015-08-14)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘./DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘DeepBlueR’ version ‘0.99.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .gitignore
  ..Rcheck
  .git
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘DeepBlueR’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... WARNING
Found the following directory with the name of a check directory:
  ./..Rcheck
Most likely, these were included erroneously.
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignette without corresponding PDF/HTML:
   ‘DeepBlue.Rmd’

* checking running R code from vignettes ...
   ‘DeepBlue.Rmd’ using ‘UTF-8’ ... OK
 OK
* checking re-building of vignette outputs ...Warning in file.copy(pkgdir, vd2, recursive = TRUE) : too deep nesting
Warning in file.copy(pkgdir, vd2, recursive = TRUE) : too deep nesting
 OK
* checking PDF version of manual ... OK
* DONE

Status: 2 WARNINGs, 1 NOTE
See
  ‘/home/albrecht/DeepBlue/DeepBlueR/..Rcheck/00check.log’
for details.

-- 

⇒  R CMD BiocCheck .
* This is BiocCheck, version 1.6.1.
* BiocCheck is a work in progress. Output and severity of issues may
  change.
* Installing package...
Note: the specification for S3 class “AsIs” in package ‘DBI’ seems equivalent to one from package ‘BiocGenerics’: not turning on duplicate class definitions for this class.
* Checking if other packages can import this one...
* Checking to see if we understand object initialization....
    * CONSIDER: Clarifying how objects ‘write.table, download.file’
      (used in deepblue.batch_export_results,
      deepblue.switch_get_request_data) were initialized. Maybe they
      are part of a data set loaded with data(), or perhaps part of an
      object referenced in with() or within().
* Checking vignette directory...
* Unknown package type, checking vignette directories...
* # of chunks: 23, # of eval=FALSE: 3 (13%)
* Checking version number...
* Checking version number validity...
    * RECOMMENDED: y of x.y.z version should be even in release
* Checking R Version dependency...
* Checking biocViews...
* Checking that biocViews are present...
* Checking that biocViews come from the same category...
    * RECOMMENDED: Use biocViews from one category only (one of
      Software, ExperimentData, AnnotationData)
See http://bioconductor.org/developers/how-to/biocViews/
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches dir/tarball name...
* Checking for Version field...
* Checking for valid maintainer...
* Checking unit tests...
    * CONSIDER: Adding unit tests.  We strongly encourage them. See
      http://www.bioconductor.org/developers/how-to/unitTesting-guidelines/.
* Checking native routine registration...
* Checking for deprecated package usage...
* Checking parsed R code in R directory, examples, vignettes...
* Checking for direct slot access...
* Checking for T...
* Checking for F...
* Checking for browser()...
* Checking for <<-...
* Checking for library/require of DeepBlueR...
* Checking DESCRIPTION/NAMESPACE consistency...
* Checking function lengths...........................................................
* The longest function is 91 lines long
* The longest 5 functions are:
* deepblue.batch_export_results() (R/batchExport.R, line 18): 91 lines
* xml.rpc() (R/deepblue.R, line 2691): 50 lines
* deepblue.column_types() (R/internalFunctions.R, line 183): 41 lines
* deepblue.switch_get_request_data() (R/internalFunctions.R, line 74):
  36 lines
* _anonymous_.29() (R/methods_DeepBlueCommand.R, line 29): 34 lines
* Checking man pages...
    * RECOMMENDED: Add non-empty \value sections to the following man
      pages:
      deepblue.column_types.Rd, deepblue.debug.VERBOSE.Rd,
      deepblue.parse_gtf.Rd, deepblue.switch_get_request_data.Rd,
      deepblue.URL.Rd, deepblue.USER_KEY.Rd, deepblue.wait_request.Rd,
      show-DeepBlueCommand-method.Rd, xml.rpc.Rd
* Checking exported objects have runnable examples...
    * CONSIDER: Adding runnable examples to the following man pages
      which document exported objects:
      deepblue.download_request_data.Rd
* Checking package NEWS...
* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * CONSIDER: Shortening lines; 385 lines (6%) are > 80 characters
      long.
    * CONSIDER: Replacing tabs with 4 spaces; 55 lines (0%) contain
      tabs.
    * CONSIDER: Indenting lines with a multiple of 4 spaces; 586 lines
      (9%) are not.
  See http://bioconductor.org/developers/how-to/coding-style/
* Checking for canned comments in man pages...
* Checking if package already exists in CRAN...
* Checking for support site registration...
* Maintainer is registered at support site!


Summary:
REQUIRED count: 0
RECOMMENDED count: 3
CONSIDERATION count: 6
For detailed information about these checks, see the BiocCheck
vignette, available at
http://bioconductor.org/packages/3.2/bioc/vignettes/BiocCheck/inst/doc/BiocCheck.html#interpreting-bioccheck-output

**Comment by mlist** [comment]
Update:

R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded
