### ISSUE TITLE
PDF/HTML vignette output?

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#16]
Sorry, what does this message say? (from the CMD check command)

> checking package vignettes in ‘inst/doc’ ... WARNING
> Package vignette without corresponding PDF/HTML:
> ‘DeepBlue.Rmd’

**Comment by mlist** [comment]
The problem was that the vignette is supposed to be DeepBlueR.Rmd. The old vignette file had to be manually deleted.
