### ISSUE TITLE
Bioconductor coding style

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#20]
I am looking how to find it automatically in sublime or Rstudio

CONSIDER: Shortening lines; 385 lines (6%) are > 80 characters long.
CONSIDER: Replacing tabs with 4 spaces; 55 lines (0%) contain tabs.
CONSIDER: Indenting lines with a multiple of 4 spaces; 586 lines (9%) are not. See http://bioconductor.org/developers/how-to/coding-style/

**Comment by mlist** [comment]
I reduced these numbers previously by going through each file individually.
With the remaining lines, I think the issue is probably with the
documentation.

**Comment by felipealbrecht** [comment]
I dont know why it grew, but as it is just a consideration, lets dont spend our time on this.

* Checking formatting of DESCRIPTION, NAMESPACE, man pages, R source,
  and vignette source...
    * CONSIDER: Shortening lines; 401 lines (5%) are > 80 characters
      long.
    * CONSIDER: Replacing tabs with 4 spaces; 27 lines (0%) contain
      tabs.
    * CONSIDER: Indenting lines with a multiple of 4 spaces; 594 lines
      (8%) are not.
