### ISSUE TITLE
Support 'struct' in the download_request_data

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#27]
A new command (coverage) returns a dictionary/struct/map with a set of dictionary/struct/map. Currently the download_request_data does not support this type, but I think that it is simple to convert this data do a R object using the already existing xmlrpc functions.

This function is not already in the live version.

Example of the output:

{'coverages': {'chrX': {'total': 1483495, 'coverage': 0.9554, 'size': 155270560}, 'chr13': {'total': 1132457, 'coverage': 0.9833, 'size': 115169878}, 'chr12': {'total': 2964677, 'coverage': 2.2149, 'size': 133851895}, 'chr11': {'total': 2899893, 'coverage': 2.148, 'size': 135006516}, 'chr10': {'total': 2420026, 'coverage': 1.7855, 'size': 135534747}, 'chr17': {'total': 3111151, 'coverage': 3.8317, 'size': 81195210}, 'chr16': {'total': 2134123, 'coverage': 2.3619, 'size': 90354753}, 'chr15': {'total': 1820040, 'coverage': 1.7751, 'size': 102531392}, 'chr14': {'total': 1692055, 'coverage': 1.5762, 'size': 107349540}, 'chr19': {'total': 3237248, 'coverage': 5.4749, 'size': 59128983}, 'chr18': {'total': 1012202, 'coverage': 1.2964, 'size': 78077248}, 'chr22': {'total': 1204818, 'coverage': 2.3484, 'size': 51304566}, 'chr20': {'total': 1436177, 'coverage': 2.2787, 'size': 63025520}, 'chr21': {'total': 589069, 'coverage': 1.2239, 'size': 48129895}, 'chr7': {'total': 2623790, 'coverage': 1.6487, 'size': 159138663}, 'chr6': {'total': 3309649, 'coverage': 1.9342, 'size': 171115067}, 'chr5': {'total': 2737174, 'coverage': 1.513, 'size': 180915260}, 'chr4': {'total': 2204447, 'coverage': 1.1532, 'size': 191154276}, 'chr3': {'total': 3096812, 'coverage': 1.5639, 'size': 198022430}, 'chr2': {'total': 3900776, 'coverage': 1.6039, 'size': 243199373}, 'chr1': {'total': 5292444, 'coverage': 2.1233, 'size': 249250621}, 'chr9': {'total': 2336737, 'coverage': 1.6548, 'size': 141213431}, 'chr8': {'total': 2050838, 'coverage': 1.4012, 'size': 146364022}}})

**Comment by mlist** [comment]
Do you have an example request ID to test this?

**Comment by felipealbrecht** [comment]
Not yet. Only when the new version be live.

**Comment by mlist** [comment]
Can we close this now? Is there a test case?

**Comment by felipealbrecht** [comment]
Yes! 





On Fri, Jun 24, 2016 at 1:20 PM +0200, "Markus List" <notifications@github.com> wrote:












Can we close this now? Is there a test case?
