### ISSUE TITLE
False counts in deepblue_collection_experiments_count

### ISSUE THREAD

**Issue by mlist** [MPIIComputationalEpigenetics/DeepBlueR#28]
Example:

`biosources_list = deepblue_collection_experiments_count(project = "BLUEPRINT Epigenome", controlled_vocabulary = "biosources")
dplyr::arrange(biosources_list, -count)`

        id                                                                       name count
1  bs15897                                          peripheral blood mononuclear cell    35
2  bs16217                                         alternatively activated macrophage    34

I'd expect that there are 35 experiments associated with 'peripheral blood mononuclear cell'. But:

`deepblue_list_experiments(project = "BLUEPRINT Epigenome", biosource = "peripheral blood mononuclear cell")`

yields only 9:

      id                                                      name
1 e54435   S00XVLH1.ERX941024.H3K27ac.bwa.GRCh38.20150529.bedgraph
2 e54420   S00XVLH1.ERX941022.H3K4me3.bwa.GRCh38.20150529.bedgraph
3 e55176        S00XVLH1.ERX941024.H3K27ac.bwa.GRCh38.20150527.bed
4 e55171        S00XVLH1.ERX941022.H3K4me3.bwa.GRCh38.20150527.bed
5 e55120 S00XVLH1.ERX941026.H3K27me3.bwa.GRCh38.broad.20150527.bed
6 e55102  S00XVLH1.ERX941025.H3K4me1.bwa.GRCh38.broad.20150527.bed
7 e54468   S00XVLH1.ERX941025.H3K4me1.bwa.GRCh38.20150529.bedgraph
8 e54484  S00XVLH1.ERX941026.H3K27me3.bwa.GRCh38.20150529.bedgraph
9 e54493     S00XVLH1.ERX943235.Input.bwa.GRCh38.20150529.bedgraph

Is this a server issue?

**Comment by felipealbrecht** [comment]
Hey, I just tested the command and it is working.

I really believe that the number '35' and '34' are the array indexes.

For example: (in this case, it is position 38)

> biosources_list = deepblue_collection_experiments_count(project = "BLUEPRINT Epigenome", controlled_vocabulary = "biosources") 
> biosources_list[[38]]
[[1]]
[1] "bs15897"

[[2]]
[1] "peripheral blood mononuclear cell"

[[3]]
[1] 9

**Comment by felipealbrecht** [comment]
The same for the the another biosource:


[[42]]
[[42]][[1]]
[1] "bs16217"

[[42]][[2]]
[1] "alternatively activated macrophage"

[[42]][[3]]
[1] 85
