### ISSUE TITLE
Use case 3 is too slow

### ISSUE THREAD

**Issue by felipealbrecht** [MPIIComputationalEpigenetics/DeepBlueR#30]
> liver_biosource_names = c()

> for (biosource in biosources)
+ {
+     related_biosources = deepblue_get_biosource_related(biosource)
+     related_biosources_names = deepblue_extract_names(related_biosources)
+     liver_biosource_names =c(liver_biosource_names, related_biosources_names)
+ }
Called method: deepblue_get_biosource_related
Reported status was: okay
Called method: deepblue_extract_names
Reported status was: okay
Called method: deepblue_get_biosource_related
Reported status was: okay
Called method: deepblue_extract_names
Reported status was: okay

.... and nothing after ....

**Comment by felipealbrecht** [comment]
It works, but it is too slow.

**Comment by felipealbrecht** [comment]
Okay, it fails: - I believe that the problem is exactly the same with the use case 2.


Called method: deepblue_list_experiments
Reported status was: okay

> hsc_experiment_names = deepblue_extract_names(experiments)
Called method: deepblue_extract_names
Reported status was: error
Error in deepblue_extract_names(experiments) : 
  Error at parameter [0:list]: Parameter of type struct was given. Expected type array.

**Comment by felipealbrecht** [comment]
Waiting for issue #31

**Comment by mlist** [comment]
Usecase 3 currently fails despite the recent fix. Likely an issue in the DeepBlue server. No liver related samples can be found in BLUEPRINT Epigenome (also not in the DeepBlue web interface).

**Comment by mlist** [comment]
Ok, there are no liver samples in BLUEPRINT. This usecase was broken before from the start.

**Comment by mlist** [comment]
I changed the usecase for now to use regulatory t cells with few experiments.
